syntax = "proto3";

package Fossa.Messaging.Messages.Events;

option csharp_namespace = "Fossa.Messaging.Messages.Events";

message CompanyChangedProtoEvent {
  int64  CompanyId   = 1;
  string Name        = 2;
  string CountryCode = 3;
}

message CompanyDeletedProtoEvent {
  int64 CompanyId = 1;
}

message Address {
  string City        = 1;
  string CountryCode = 2;
  string Line1       = 3;
  string Line2       = 4;
  string PostalCode  = 5;
  string Subdivision = 6;
}

message BranchChangedProtoEvent {
  int64   BranchId   = 1;
  int64   CompanyId  = 2;
  string  Name       = 3;
  Address Address    = 4;
  string  TimeZoneId = 5;
}

message BranchDeletedProtoEvent {
  int64 BranchId = 1;
}

message EmployeeChangedProtoEvent {
  int64  EmployeeId           = 1;
  int64  CompanyId            = 2;
  string FirstName            = 3;
  string LastName             = 4;
  string FullName             = 5;
  string JobTitle             = 6;
  int64  AssignedBranchId     = 7;
  int64  AssignedDepartmentId = 8;
  int64  ReportsToId          = 9;
}

message EmployeeDeletedProtoEvent {
  int64 EmployeeId = 1;
}

message DepartmentChangedProtoEvent {
  int64  DepartmentId       = 1;
  int64  CompanyId          = 2;
  string Name               = 3;
  int64  ManagerId          = 4;
  int64  ParentDepartmentId = 5;
}

message DepartmentDeletedProtoEvent {
  int64 DepartmentId = 1;
}
