<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Build">
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>ad336f2b-09b8-4c53-96cb-ed9913b583f1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\..\Source\Messaging\Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IdGen.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

</Project>
